// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4zkUy06ya8DVv4G6G6sYjOS8DneO-jFY',
    appId: '1:60621094210:web:4d7a8c6089985f6e229cdb',
    messagingSenderId: '60621094210',
    projectId: 'todoapp-910bf',
    authDomain: 'todoapp-910bf.firebaseapp.com',
    storageBucket: 'todoapp-910bf.appspot.com',
    measurementId: 'G-LX491R31QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvSn-sxCE4th24BBTp-0StzZ5GPOdksOc',
    appId: '1:60621094210:android:2fde677a9c535f80229cdb',
    messagingSenderId: '60621094210',
    projectId: 'todoapp-910bf',
    storageBucket: 'todoapp-910bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClg2ZHg6UFarTK1abZo3Ji3IqiCOU7oK8',
    appId: '1:60621094210:ios:387a101fd8822bec229cdb',
    messagingSenderId: '60621094210',
    projectId: 'todoapp-910bf',
    storageBucket: 'todoapp-910bf.appspot.com',
    iosClientId: '60621094210-bni3uaqg1mi09953peb51crqmnqiqb7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
